### ISSUE TITLE
Implement fields and model in Django-like style

### ISSUE THREAD

**Issue by i8enn** [i8enn/elasticsearch-odm-aio#1]
Within this task need implement base fields and model in Django-like style.

Full fields implementation is not possible until validators implementation complete. 

- [x] Fields in Django-like style
- [x] Meta classes for models in Django-like style (Options)
- [x] Models in Django-like style

**Comment by i8enn** [comment]
Implemented
