### ISSUE TITLE
Implement interaction class for Querysets and Elasticsearch-aio library

### ISSUE THREAD

**Issue by i8enn** [i8enn/elasticsearch-odm-aio#3]
Within this task need implement class for interaction QuerySets methods and elasticsearch-async library.

- [ ] Implement interaction class
- [ ] Integration interaction class and QuerySets
- [ ] Implement temporary integration ES connection and this ODM
