### ISSUE TITLE
Implement validation in model-level

### ISSUE THREAD

**Issue by i8enn** [i8enn/elasticsearch-odm-aio#6]
Within this task need implement validation in model-level in Django-like style.

- [ ] Error class (need for collecting validation errors)
- [ ] Base validator class
- [ ] Methods for field-level validation
- [ ] Methods for model-level validation
- [ ] Standard validators set
